### PR TITLE
Cherry-picked changes from yli

### PR DESCRIPTION
**Pull request by pb-cdunn**
This is identical to #14, but based on master instead of merged.
This was simple:
```sh
git checkout master
git pull origin
git remote add yli git@github.com:ylipacbio/blasr_libcpp.git
git fetch yli
git cherry-pick e9b1136  #Replace Tokenize with...
git cherry-pick 147f9ce  #Pass cigarUseSeqMatch through...
git diff yli/master
# identical!
git push cd master:yli-14
```
"Cherry-picking" is like "rebasing", but just one commit at a time. Think of the edges of the tree as UNIX patch-files. Cherry-pick simply applies that patch-file at another node in the tree.

But in the future, you're better off with this workflow:
```sh
git checkout -b my-feature
#...edit
git add .
git commit -m 'message'
git fetch origin
git rebase origin/master
git push yli my-feature
```
Then you'll have a nice linear history, seen in [`git lola`](http://blog.kfish.org/2010/04/git-lola.html).

With rebasing (or cherry-picking), the history looks like this:
```
* 0b7f6e7 (HEAD, cd/yli-14, master) Pass cigarUseSeqMatch through BAMPrinter, enabling cigar with x and =.
* ad0db78 Replace Tokenize with Splice and fix a bug. Also test if a change which breaks blasr can be caught somewhere in p4 build.
*   98a302a (tag: p4-mainline, origin/master, origin/HEAD) Merge pull request #13 from PacificBiosciences/mjhsieh-patch-1
|\
| * 0e8803d (origin/mjhsieh-patch-1) Default Value for HTSLIB is wrong.
|/
*   1b70c01 Merge pull request #12 from pb-cdunn/master
|\
| * 570fea7 (cd/master) HTSLIB_INCLUDE may come from environment.
|/
*   df1886b Merge pull request #11 from pbjd/master
...
```

Without rebasing, the history looks like this:
```
* 0dd9daa (yli/master, yli-master) Revert "'build icon' points to private repo"
* 147f9ce Pass cigarUseSeqMatch through BAMPrinter, enabling cigar with x and =.
* 7789519 'build icon' points to private repo
*   d29c83b Merge remote-tracking branch 'upstream/master'
|\
| *   98a302a (tag: p4-mainline, origin/master, origin/HEAD) Merge pull request #13 from PacificBiosciences/mjhsieh-patch-1
| |\
| | * 0e8803d (origin/mjhsieh-patch-1) Default Value for HTSLIB is wrong.
| |/
| *   1b70c01 Merge pull request #12 from pb-cdunn/master
| |\
| | * 570fea7 (cd/master) HTSLIB_INCLUDE may come from environment.
| |/
| *   df1886b Merge pull request #11 from pbjd/master
| |\
| | * d853997 Only set HTSLIB_INCLUDE if not already set
| |/
| *   4cffdff Merge pull request #9 from pb-cdunn/curl-k
| |\
| | * 2016544 curl -k
| |/
| *   abdac25 Merge pull request #7 from pb-cdunn/herb
| |\
| | * 87b4cd2 from herb
| * | a6433a6 'build status icon' point to pacbio repo
| |/
| * 781d6f0 Create README.md
| *   e6c1b18 Merge pull request #5 from pbjd/master
| |\
| | * d399f10 Remove hdf lib reference from travis file
| | *   64e0ebd Merge branch 'master' of github.com:pbjd/blasr_libcpp
| | |\
| | | * 20dd91a Fix hdf breakage?
| | * | 0889b1d Interim fix
| | |/
| | * c58cd39 Adding yaml file
| * |   7e3ac66 Merge pull request #6 from pb-cdunn/herb
| |\ \
| | |/
| |/|
| | * 33f6c21 trying to get shared libraries in the Perforce build
| |/
* | e9b1136 Replace Tokenize with Splice and fix a bug. Also test if a change which breaks blasr can be caught somewhere in p4 build.
* | 5b6d76d compile with nohdf nopbbam
* | e7bae58 Add .travis.yml
|/
*   29ac4be Merge pull request #3 from ylipacbio/feat
|\
| * 528dc0e Revert "Update Makefile"
|/
*   b4c30cf Merge pull request #2 from ylipacbio/master
```

### CODE REVIEW

**Comment by ylipacbio** [comment]
Thanks, Chris! With rebasing, the history looks much better!

**Comment by pb-cdunn** [comment]
@ylipacbio wrote:
> This pull request should break p4 build unless we change p4 code accordingly.

I guess you're talking about the 2nd commit, right? That changes the API of some templates.

In that case, the 2nd commit should have its own pull-request. Then, in order to pull it into p4, we'll need to start storing SHA1s in p4. Then, you can change the SHA1 in the same commit where you alter p4-hosted code.

But it's better if you can avoid backward-incompatible changes. Consider writing new templates (that might need new names), and keeping the old versions along with the new. Then, this can go into p4 immediately. Later, after you update the code which uses this, you can remove the old code.

**Comment by ylipacbio** [comment]
Thanks Chris!

Actually I am talking about the first commit 'Replace Tokenize with Splice', which would break the p4 build. 

This is one thing that concerned me. Backward-compatible changes are good, but sometimes backward-incompatible changes are unavoidable. We will need a 'protocol' regarding how to submit backward-incompatible changes, since the main.cpp of blasr and blasr_libcpp are saved in different places and both need to be tested from p4 build as well as git clone build. Adding SHA1 to p4 sounds necessary.

**Comment by pb-cdunn** [comment]
And please don't take that as criticism. I'm a stickler, but a messier history is not a tragedy. I am so happy that you wrote unit-tests for your new code. Those actually run in Travis!

If you need the backward-incompatible change quickly, let me know. We could push the switch to SHA1s a little ahead of my mental schedule, and it would make herb very happy.

One suggestion: A backward-incompatible change really deserves its own bugzilla-tracking. And even though it's great that you mentioned it in the pull-request, maybe we should follow the convention of making it clear on the top of the commit message.

In git, the commit message should look like this:
```
a few words of summary
                              < BLANK LINE
more stuff
* maybe a bullet
* or two
```
Then `git log --onenline` will show the top line, and `git log -p` will show nearly everything.

**Comment by pb-cdunn** [comment]
> Adding SHA1 to p4 sounds necessary.

Yes. I'm thinking early next week.

> Actually I am talking about the first commit 'Replace Tokenize with Splice', which would break the p4 build.

Really? How? Just curious. Do you mean a Chef test would fail? Or do you mean that `Tokenize()` was used by consumers? If the latter, you could just leave it in for now. Otherwise, I'd really like to see a bugzilla# specific to the change.

**Comment by ylipacbio** [comment]
I don't need the backward-incompatible change right now, it is mainly a toy case for me to play with the new dev mode. But I do think it's nice to have SHA1 in the p4 build earlier, which enables more precise version control over blasr and blasr_libcpp. Early next week sounds cool!



Also thank you for pointing out the correct format for commit message.

**Comment by ylipacbio** [comment]
I mean Tokenize() was called by LoadPulses in the blasr package.

**Comment by pb-cdunn** [comment]
If the change is not bound for p4 immediately, then please don't merge it to master. It should remain on its own branch for now. Ok? Maybe that's already obvious.

**Comment by pb-cdunn** [comment]
Now, prepare to have your mind blown.
* https://help.github.com/articles/github-flavored-markdown/
* https://help.github.com/articles/writing-on-github/

- [ ] a bigger project
  - [x] first subtask #1234
  - [X] follow up subtask #4321
  - [ ] final subtask cc @mention
- [ ] a separate task

**Comment by ylipacbio** [comment]
I created this pull request to (1) help me familiarize with git and (2) bring up a question regarding how to check in changes like this.

**Comment by pb-cdunn** [comment]
That's what I thought. Good.

**Pull request closed without merging**
