### PR TITLE
BAM Spec v3.0b7, support read group item Ipd:Frame and etc.

### PR DESCRIPTION
**Pull request by ylipacbio**

### CODE REVIEW

**Comment by ylipacbio** [comment]
Chris, my git log looks ugly... 
Any solution to this?

**Comment by ylipacbio** [comment]
Hi Chris, I want to get a clean 'identical' fork from pacbio blasr_libcpp master without deleting my repo, and then apply a little commit and then create a pull request. How to do that?  Thank you!

**Comment by pb-cdunn** [comment]
Lots of ways. Wanna call me? Easier to explain that way.

**Comment by pb-cdunn** [comment]
Simple way:
```sh
git checkout -b old-master
git push origin old-master
git remote add upstream git@github.com:PacificBiosciences/blasr_libcpp.git
git fetch upstream
git checkout -B master upstream/master
git push -f origin master
# write some code, add, and commit
git push origin master
# then create the pull-request
```

**Pull request merged**
