### PR TITLE
Makefile changes

### PR DESCRIPTION
**Pull request by pb-cdunn**
Any objections?

### CODE REVIEW

**Comment by pbjd** [comment]
Interesting use of override.  What was the problem with dependencies?

**Comment by pb-cdunn** [comment]
Proper use of override. Lets you do this:

    make CXXFLAGS=-g

Very helpful when running valgrind on the gtest.

Dependencies have been a RPITA. It would be ok to have a separate `depend` target, but these are always generating `*.d` during compilation. That is a recipe for pain because when you `git checkout` you could add or remove headers. In that case, the current `*.d` can be wrong, which is why we've had such problems with incremental builds under mobs.

So a proper `depend` rule would be best, but that takes time. And with `ccache g++`, there is really no point. **ccache** is much more reliable than the `*.d` files. It actually looks everything.

**Comment by ylipacbio** [comment]
Great job, Chris!

I really like the idea of having a separate depend rule.
*.d had caused problems which are hard to track, and that's why I almost always have to clean everything everytime I compile.

Overriding CXXFLAGS seems attractive because I always have to switch between '-O3' and '-g -ggdb', but I am not a Makefile master to speak if it is safe to do so (overriding vars in makefile sounds tricky). Anyone to comment?

**Comment by pb-cdunn** [comment]
### New targets
Just for you I've added some new targets:
* `all-debug`
* `all-opt`
* `all-depend`

I'm not certain that the new `depend` rules are robust, but it doesn't matter because they're only used explicitly. In general, you should prefer **ccache**.

### CXXFLAGS
Much better is the use of CXXFLAGS for configure.py. Now, in blasr (separate pull-request) you can specify your CXXFLAGS when you run configure.py there. It will propagate CXXFLAGS to the submodule. You can still override it (I think) on the command-line when you run make, if you want. Super-convenient.

At some point, we might switch to **cmake**, which is good as long as we don't use its ridiculously complicated find_packages() function.

**Comment by pb-cdunn** [comment]
If you notice a problem, let me know. I can probably fix it faster than we can revert.

**Pull request merged**
